#!/bin/bash
# ============================================
# SOC-PME Appliance - VLAN & Network Setup
# ============================================
# Configure VLANs and network interfaces for PME appliance
# Run as root on Debian 12 / Ubuntu 22.04
# ============================================

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${GREEN}╔════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║      SOC-PME Network Configuration         ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════╝${NC}"

# ============================================
# CONFIGURATION - Modify as needed
# ============================================
WAN_INTERFACE="eth0"           # Interface vers Internet
LAN_INTERFACE="eth1"           # Interface vers le switch (trunk)

# VLANs Configuration
VLAN_SOC_ID=10
VLAN_SOC_NETWORK="172.16.10.0/24"
VLAN_SOC_IP="172.16.10.1"

VLAN_SECURITY_ID=20
VLAN_SECURITY_NETWORK="172.16.20.0/24"
VLAN_SECURITY_IP="172.16.20.1"

VLAN_LAN_ID=30
VLAN_LAN_NETWORK="172.16.30.0/24"
VLAN_LAN_IP="172.16.30.1"
VLAN_LAN_DHCP_START="172.16.30.100"
VLAN_LAN_DHCP_END="172.16.30.254"

# ============================================
# STEP 1: Install Prerequisites
# ============================================
echo -e "\n${YELLOW}[1/6] Installing prerequisites...${NC}"
apt-get update -qq
apt-get install -y -qq vlan nftables dnsmasq bridge-utils iproute2

# Enable 802.1Q VLAN module
modprobe 8021q
echo "8021q" >> /etc/modules-load.d/8021q.conf

# ============================================
# STEP 2: Create VLAN Interfaces
# ============================================
echo -e "\n${YELLOW}[2/6] Creating VLAN interfaces...${NC}"

# Create VLAN interfaces
cat > /etc/network/interfaces.d/vlans <<EOF
# SOC-PME VLAN Configuration
# Generated by setup-network-pme.sh

# VLAN 10 - SOC Management
auto ${LAN_INTERFACE}.${VLAN_SOC_ID}
iface ${LAN_INTERFACE}.${VLAN_SOC_ID} inet static
    address ${VLAN_SOC_IP}
    netmask 255.255.255.0
    vlan-raw-device ${LAN_INTERFACE}

# VLAN 20 - Security/DMZ
auto ${LAN_INTERFACE}.${VLAN_SECURITY_ID}
iface ${LAN_INTERFACE}.${VLAN_SECURITY_ID} inet static
    address ${VLAN_SECURITY_IP}
    netmask 255.255.255.0
    vlan-raw-device ${LAN_INTERFACE}

# VLAN 30 - LAN Users
auto ${LAN_INTERFACE}.${VLAN_LAN_ID}
iface ${LAN_INTERFACE}.${VLAN_LAN_ID} inet static
    address ${VLAN_LAN_IP}
    netmask 255.255.255.0
    vlan-raw-device ${LAN_INTERFACE}
EOF

echo -e "${GREEN}✓ VLAN interfaces configured${NC}"

# ============================================
# STEP 3: Configure NFTables Firewall
# ============================================
echo -e "\n${YELLOW}[3/6] Configuring NFTables firewall...${NC}"

cat > /etc/nftables.conf <<'NFTABLES'
#!/usr/sbin/nft -f
# ============================================
# SOC-PME NFTables Firewall Configuration
# NIST CSF Aligned - PROTECT Function
# ============================================

flush ruleset

# Define variables
define WAN_IF = "eth0"
define VLAN_SOC = "eth1.10"
define VLAN_SEC = "eth1.20"
define VLAN_LAN = "eth1.30"

define SOC_NET = 172.16.10.0/24
define SEC_NET = 172.16.20.0/24
define LAN_NET = 172.16.30.0/24

define RFC1918 = { 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16 }

table inet filter {
    # ========== INPUT CHAIN ==========
    chain input {
        type filter hook input priority 0; policy drop;
        
        # Allow established/related connections
        ct state established,related accept
        
        # Allow loopback
        iif "lo" accept
        
        # Allow ICMP (ping)
        ip protocol icmp limit rate 10/second accept
        ip6 nexthdr icmpv6 limit rate 10/second accept
        
        # Allow SSH from SOC VLAN only
        iifname $VLAN_SOC tcp dport 22 accept
        
        # Allow Kibana from SOC VLAN
        iifname $VLAN_SOC tcp dport 5601 accept
        
        # Allow n8n from SOC VLAN
        iifname $VLAN_SOC tcp dport 5678 accept
        
        # Allow Homepage from SOC VLAN
        iifname $VLAN_SOC tcp dport 80 accept
        
        # Allow DHCP from LAN VLAN
        iifname $VLAN_LAN udp dport { 67, 68 } accept
        
        # Allow DNS from all internal VLANs
        iifname { $VLAN_SOC, $VLAN_SEC, $VLAN_LAN } udp dport 53 accept
        
        # Allow Syslog from Security VLAN
        iifname $VLAN_SEC udp dport 5514 accept
        iifname $VLAN_SEC tcp dport 5514 accept
        
        # Drop invalid packets
        ct state invalid drop
        
        # Log dropped packets
        log prefix "[NFTABLES-DROP] " flags all counter drop
    }
    
    # ========== FORWARD CHAIN ==========
    chain forward {
        type filter hook forward priority 0; policy drop;
        
        # Allow established/related
        ct state established,related accept
        
        # --- VLAN SOC (10) Rules ---
        # SOC can access everything (admin)
        iifname $VLAN_SOC accept
        
        # --- VLAN Security (20) Rules ---
        # Security can access Internet
        iifname $VLAN_SEC oifname $WAN_IF accept
        # Security can access LAN (limited)
        iifname $VLAN_SEC oifname $VLAN_LAN tcp dport { 80, 443 } accept
        
        # --- VLAN LAN (30) Rules ---
        # LAN can access Internet
        iifname $VLAN_LAN oifname $WAN_IF accept
        # LAN can access Security VLAN services
        iifname $VLAN_LAN oifname $VLAN_SEC tcp dport { 80, 443, 25, 587, 993 } accept
        # LAN cannot access SOC VLAN
        iifname $VLAN_LAN oifname $VLAN_SOC drop
        
        # Log dropped
        log prefix "[NFTABLES-FWD-DROP] " flags all counter drop
    }
    
    # ========== OUTPUT CHAIN ==========
    chain output {
        type filter hook output priority 0; policy accept;
    }
}

# ========== NAT TABLE ==========
table ip nat {
    chain prerouting {
        type nat hook prerouting priority -100; policy accept;
    }
    
    chain postrouting {
        type nat hook postrouting priority 100; policy accept;
        
        # Masquerade all internal networks to WAN
        oifname $WAN_IF ip saddr $RFC1918 masquerade
    }
}
NFTABLES

# Enable and start nftables
systemctl enable nftables
systemctl restart nftables

echo -e "${GREEN}✓ NFTables firewall configured${NC}"

# ============================================
# STEP 4: Configure DHCP Server (dnsmasq)
# ============================================
echo -e "\n${YELLOW}[4/6] Configuring DHCP server...${NC}"

cat > /etc/dnsmasq.d/soc-pme.conf <<EOF
# SOC-PME DHCP & DNS Configuration

# Interface binding
interface=${LAN_INTERFACE}.${VLAN_LAN_ID}
bind-interfaces

# DHCP for VLAN 30 (LAN)
dhcp-range=interface:${LAN_INTERFACE}.${VLAN_LAN_ID},${VLAN_LAN_DHCP_START},${VLAN_LAN_DHCP_END},24h
dhcp-option=interface:${LAN_INTERFACE}.${VLAN_LAN_ID},option:router,${VLAN_LAN_IP}
dhcp-option=interface:${LAN_INTERFACE}.${VLAN_LAN_ID},option:dns-server,${VLAN_LAN_IP}

# DNS upstream (can be changed to internal DNS)
server=8.8.8.8
server=1.1.1.1

# Local domain
domain=soc-pme.local
local=/soc-pme.local/

# Static DNS entries
address=/kibana.soc-pme.local/${VLAN_SOC_IP}
address=/siem.soc-pme.local/${VLAN_SOC_IP}
address=/soar.soc-pme.local/${VLAN_SOC_IP}
address=/portal.soc-pme.local/${VLAN_SOC_IP}

# Log DNS queries (for security monitoring)
log-queries
log-facility=/var/log/dnsmasq.log
EOF

systemctl enable dnsmasq
systemctl restart dnsmasq

echo -e "${GREEN}✓ DHCP server configured${NC}"

# ============================================
# STEP 5: Enable IP Forwarding
# ============================================
echo -e "\n${YELLOW}[5/6] Enabling IP forwarding...${NC}"

cat > /etc/sysctl.d/99-soc-pme.conf <<EOF
# SOC-PME Network Settings
net.ipv4.ip_forward = 1
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1
net.ipv4.icmp_echo_ignore_broadcasts = 1
net.ipv4.conf.all.log_martians = 1
net.ipv4.conf.default.log_martians = 1
net.ipv4.conf.all.accept_source_route = 0
net.ipv4.conf.default.accept_source_route = 0
net.ipv6.conf.all.forwarding = 1
EOF

sysctl -p /etc/sysctl.d/99-soc-pme.conf

echo -e "${GREEN}✓ IP forwarding enabled${NC}"

# ============================================
# STEP 6: Create SOC-PME Directories
# ============================================
echo -e "\n${YELLOW}[6/6] Creating data directories...${NC}"

mkdir -p /opt/soc-pme/{data,logs,config,backup}
mkdir -p /opt/soc-pme/data/{elasticsearch,n8n}
mkdir -p /opt/soc-pme/logs/{suricata,zeek,syslog}
chmod -R 755 /opt/soc-pme

echo -e "${GREEN}✓ Directories created${NC}"

# ============================================
# Summary
# ============================================
echo -e "\n${GREEN}╔════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║      SOC-PME Network Setup Complete!       ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${YELLOW}VLANs Configured:${NC}"
echo -e "  • VLAN 10 (SOC):      ${VLAN_SOC_IP}/24"
echo -e "  • VLAN 20 (Security): ${VLAN_SECURITY_IP}/24"
echo -e "  • VLAN 30 (LAN):      ${VLAN_LAN_IP}/24 (DHCP: ${VLAN_LAN_DHCP_START}-${VLAN_LAN_DHCP_END})"
echo ""
echo -e "${YELLOW}Services accessible from VLAN SOC (172.16.10.x):${NC}"
echo -e "  • Kibana SIEM:  http://${VLAN_SOC_IP}:5601"
echo -e "  • n8n SOAR:     http://${VLAN_SOC_IP}:5678"
echo -e "  • Portal:       http://${VLAN_SOC_IP}"
echo ""
echo -e "${YELLOW}Next steps:${NC}"
echo -e "  1. Connect ${LAN_INTERFACE} to a trunk port on your switch"
echo -e "  2. Configure switch VLANs (10, 20, 30)"
echo -e "  3. Run: docker compose -f docker-compose-pme.yml up -d"
echo ""
echo -e "${RED}⚠️  Reboot required to apply network changes!${NC}"
